apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s.web.com/name: db
  name: mysql-cm
data:
  mysql_custom.cnf: |-
    [client]
    default-character-set = utf8mb4
    [mysql]
    default-character-set = utf8mb4
    [mysqld]
    character-set-client-handshake = FALSE
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci
    lower_case_table_names=1
    max_allowed_packet=104857600
  init.sql: |-
    USE `dockerweb`;
    /*
    Navicat MySQL Data Transfer

    Source Server         : localhost
    Source Server Version : 50562
    Source Host           : localhost:3306
    Source Database       : dockerweb

    Target Server Type    : MYSQL
    Target Server Version : 50562
    File Encoding         : 65001

    Date: 2020-07-05 18:51:46
    */

    SET FOREIGN_KEY_CHECKS=0;

    -- ----------------------------
    -- Table structure for product
    -- ----------------------------
    DROP TABLE IF EXISTS `product`;
    CREATE TABLE `product` (
      `ID` int(11) NOT NULL AUTO_INCREMENT,
      `Name` varchar(255) DEFAULT NULL,
      `ImageID` int(11) DEFAULT NULL,
      `Price` decimal(10,2) DEFAULT NULL,
      PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

    -- ----------------------------
    -- Records of product
    -- ----------------------------
    INSERT INTO `product` VALUES ('1', 'women wigs', null, '25.00');

    -- ----------------------------
    -- Table structure for product_image
    -- ----------------------------
    DROP TABLE IF EXISTS `product_image`;
    CREATE TABLE `product_image` (
      `ID` int(11) NOT NULL AUTO_INCREMENT,
      `ProductID` int(11) DEFAULT NULL,
      `SRC` varchar(500) DEFAULT NULL,
      PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    -- ----------------------------
    -- Records of product_image
    -- ----------------------------
